name: 'Markdown link extract to json'
description: 'Extracts link from a section inside a markdown file and stores them into a json file.'
icon: 'file-text'
inputs:
  in-file:
    description: 'file name to read'
    required: true
    default: 'README.md'
  out-file:
    description: 'file name to write'
    required: true
    default: 'out.json'
  section:
    description: 'file name to write'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
